src/main.js

it isn't needed and is resulting in the request being blocked

don't send cross-origin header for image

---

.env.development
.env.production
src/config.js
src/grid/modal.js
src/grid/upload.js
src/index.html
src/main.css
src/main.js

Add ability to upload generated image to Grid.
Once uploaded:
- Wait 1.5s for media-api to index image
- Add labels
- Copy metadata from original image over
- Copy usage rights from original image over
- Add collections
Requires https://github.com/guardian/grid/pull/2652.

image upload

---

dev-nginx.yaml
package.json

8081 was in use by the metro bundler for editions

Switch port to 8082

---

src/index.html
src/main.css
src/main.js

This app can upload an image to Grid. Once it has uploaded, we display a link to the image. If we change the content of the canvas, we should remove the link to the image as it doesn't represent the same data anymore.
**before**
**after**
**before**
**after**
**before**
**after**

only show link to uploaded Grid image after upload

---

src/index.html

Converts the input into a text area to allow line returns.
Headlines can wrap multiple lines without the need to enter whitespace.
**Before**
**After**

allow headline to use soft and hard returns

---

src/index.html
src/main.css
src/main.js

Currently only three positions are available for text: top, middle, and bottom.
This change allows custom position settings, 0-100% of the available range.
Create images with text in an arbitrary location

Allow any vertical position for text

---

package-lock.json
package.json
src/config.js
src/index.html
src/main.css
src/main.js

See https://trello.com/c/lBqlvwYS/1240-support-new-swatches-for-fronts
It adds swatches, which are groups of colours used by different Editions, eg AU and UK can have different colour schemes.  Colours are easily (triviably) added and altered in config.js
All existing functionality continues, swatches enable different groups of colours to be used.
Before:
After:

Add swatches

---

src/canvas.js
src/config.js
src/index.html
src/main.js

After consulting with Katy, this removes the svg headline field as it is an unused feature.
Simpler interface w/reduced clutter.
**before**
**after**

removes the svg headline field

---

.github/workflows/cd.yml
package.json

The CD actions is currently failing because:
> *** Please tell me who you are.
Run
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
to set your account's default identity.
Omit --global to set the identity only in this repository.
fatal: empty ident name (for <runner@fv-az59.etfqdfk4xyru1l5ijc3mck2mlh.cx.internal.cloudapp.net>) not allowed
https://github.com/tschaub/gh-pages/issues/345 suggests we need to do some magic beforehand.
CD works 🙏 
n/a

perform necessary configuration for the gh-pages module

---

src/components/header.tsx

Before the react conversion, the grid link would disappear if the upload button was pressed additional times until it had finished uploading again. This was a useful feature as it would allow a user to see if the upload process had finished at a glance. This PR reintroduces this feature that was lost during the react conversion.
The grid link is not visible when an item is uploading, and becomes visible once the process has finished.

Hide the grid link if the upload button is pressed again

---

src/components/form.tsx
src/types/furniture.d.ts
src/utils/canvas.ts
src/utils/furniture-helpers.ts

This PR builds on the [convert to react](https://github.com/guardian/editions-card-builder/pull/44) changes and reuses the colour picker component to select a standfirst colour. This colour is then used in the canvas rendering for the standfirst text. 
The user should be able to set the headline text and standfirst text colour separately. See this [trello card](https://trello.com/c/VqsF3OZf/271-headline-and-standfirst-have-different-colours) for more details.

Allow multiple colours

---

src/components/colour-picker.tsx
src/styles/main.css

This PR fixes an issue with selecting custom colours, due to the options having the same Id. It fixes that issue by prepending the id with the component prop Id. This is the same way the other radio options have unique Ids. 
Pressing the second custom colour option should work as expected.

Fixes custom colours not working because of duplicate ids

---

src/utils/config.ts

This PR fixes an issue with the large font size which was causing text to overlap vertically. This issue appears to have been added erroneously in this [PR](https://github.com/guardian/editions-card-builder/pull/25/files).
The large font size should now display without any overlap issues.

Fixes large font vertical overlap

---

src/components/app.tsx
src/components/collapsible.tsx
src/components/form.tsx
src/components/header.tsx
src/styles/main.css
src/types/furniture.d.ts
src/utils/canvas.ts
src/utils/config.ts
src/utils/furniture-helpers.ts
src/utils/text-renderer.ts

This PR provides the ability to set a Kicker and Byline on a card, including the ability to change their colours separately.  It also attempts to improve the UX of the editor by moving form sections into collapsible areas. 
A user should be able to setup a combination of Headline, Kicker, Standfirst & Byline in anyway they see fit without visual glitches. In reality we would only expect to see a subset of these combined but we should aim to accommodate all situations.
The UX changes should also make the tool easier to use, especially given the now large number of input options. 
The changes to the UX, if not intuitive could cause confusion to the user. There may also be combinations of the various inputs which cause the image to be rendered in a strange or erroneous way.

Add byline and kicker

---

src/components/canvas.tsx
src/utils/canvas.ts

This PR is aimed at resolving the various performance issues that are being experienced on the Card Builder. It makes two distinct changes to attempt to improve performance: 
1. It prevents multiple requests for an image by caching a placeholder. If this placeholder is found the draw is rejected as we are loading the image in, and don't want to make a second attempt to load it. The latest furniture is preserved as a property on the CanvasCard class, this ensures no changes are lost. 
2. It adds a draw count, this is used to check if the draw promise is the latest one we care about, otherwise it discards it. This should improve performance by reducing the number of unnecessary draws. 
The performance of the tools should be improved for users, allowing them to use the tool more easily. …

Performance improvements

---

src/utils/config.ts

Source's [global colour names](https://www.theguardian.design/2a1e5182b/p/492a30-light-palette) have changed from semantic words to numbers representing approximate lightness values. This approach was considered more scalable. The word-based names are deprecated and the number-based names have been available for some time.
With 2.0.0 we have decided to declutter the API and delete the old names. The old names will no longer resolve.
With this change, I've preserved the old semantic names here to ensure teams using the card builder don't notice a difference. This change refactors the logic slightly to make the colour assignment more explicit. The alternative would be to do some renaming / destructuring, but I found the resulting code, admittedly DRYer, but more difficult to understand. …

Use new Source colour names

---

src/components/form.tsx
src/components/size-picker.tsx
src/enums/size.ts
src/styles/main.css
src/utils/canvas.ts
src/utils/config.ts

This PR restores the work done on guardian/editions-card-builder#56 with the latest font size values.
The only differences between this PR and the original are the font sizes in the config.ts file. The latest values should be:
Tablet:
HED-XL=180px
HED-L=128px
HED-M=105px
HED-S=80px
linespace=105%
Mobile:
HED-XL= 100px
HED-L=84px
HED-M=68px
HED-S=52px
linespace=105%
Standfirsts stay as they were originally
Mobile
SF-M=32px on 110%
SF-S=28px on 110%

Restore font size work

---

src/components/form.tsx

Users would like to be able to use returns in the byline. This is currently not possible with a standard text input. This PR changes the text input to be a text area, allowing users to enter returns.
Loads the card builder and select an image. In the byline section enter some text separate by returns and view the result.
Users can use returns in the byline.

Changes the byline text input to be a textarea

---

src/components/canvas.tsx

After reports of issues by users,  I investigated the problem of uploading/downloading images that didn't match what was displayed on screen. This PR is an attempt to fix a race condition which results in the upload/download options, using an outdated version of the canvas resulting in the uploaded/downloaded image not being the same as the one displayed on screen. 
I believe the cause of this is to be the canvas.toBlob function, it will wait for all pending changes to the canvas to be finished before returning, which may return in no particular order. This could mean the last returned blob is outdated. I was able to identify through console logging rapid text changed and downloading the end result, frequently the image didn't match the current canvas.
Load an image, makes a rapid set of …

Attempts to fix the to blob race condition

---

src/components/app.tsx
src/components/canvas.tsx
src/components/header.tsx

This PR moves the canvas to blob call into the header component. This has the advantage of only calling to blob when either the upload or download buttons are pressed. This means that the canvas is only turned into an image when requested rather than proactively. This should reduce the number of calls, making it more performant. This may also prevent occasions when an outdated version of image was being used for the upload/download.
Load the card builder, make many changes in rapid succession, download the result. 
The downloaded image should always match the rendered one, and the tool should be performant.

Moves the to blob call into the header component after a button press

---

src/components/form.tsx
src/components/size-picker.tsx
src/enums/size.ts
src/styles/main.css
src/utils/canvas.ts
src/utils/config.ts

This PR restores the font sizes changes which were reverted, pending a discussion. The original PR can be found [here](https://github.com/guardian/editions-card-builder/pull/60). They have now been approved, with a small change, requiring that the standfirst and byline should not be bold by default. The option for a user to set the font weight to bold will be coming in a later PR.
To test the standfirst font change, add an image, add some standfirst/byline text and observe the font should have a regular weight.
Users have the correct font options available to them.
**NB** Please forgive the typo in the branch name

Restore font size work again

---

src/components/form.tsx
src/enums/location.ts
src/types/furniture.d.ts
src/utils/canvas.ts
src/utils/config.ts
src/utils/furniture-helpers.ts

As stated in the [card](https://trello.com/c/PN5G5KdO/309-provide-multiple-byline-location-options) the users of the editions card builder would like to be able to colocate the byline with either the headline or the standfirst, using the appropriate styling. The byline appearing under the headline should be considered the default. The font for the headline byline is (Guardian Headline) Light and for the standfirst TE32 (Text Egyptian). 
This PR implements these requirements.
Add a byline and choose 'Locate under' + 'Headline' or 'Standfirst' and see the byline change location and font/size.

Allow byline positioning

---

src/utils/canvas.ts
src/utils/text-renderer.ts

This PR fixes the text overlap by setting the [text baseline](https://www.w3schools.com/tags/canvas_textbaseline.asp) option to bottom. This will mean that descenders no longer go bellow the pixel position. 
Select an image, add descenders and ascenders to the the headline and standfirst at various heights and font sizes. 
If there is never any overlap between lines.
This change make a slight difference to spaces between lines which may be undesirable.
Before:
After:

Fix text overlap

---

src/utils/canvas.ts

This PR fixes the top offset of text by adding some additional padding. This issue was introduced in a previous PR which adjusted the text baseline, causing all text to be rendered slightly higher.
Select an image, enter some text, observe the top offset of the text.
The text is rendered in the correct position.
Before: 
After:

Fixes the top offset of text

---

package-lock.json
package.json
src/utils/config.ts

This PR fixes an issues with the byline using the "Guardian Headline Light" font. Previously, when the text was initially rendered to the screen, the font was incorrect because it hadn't yet been loaded. The fix for this issue is to load the font in advance of the canvas rendering, in this case, in _config.ts_. 
This fix uses [CSS Font Loading API](https://developer.mozilla.org/en-US/docs/Web/API/FontFaceSet/load) to load the font.
Select an image, enter some text into the byline, the font should consistently be GH Light and not flicker.
The byline font is always correct.

Preload GH Light font to avoid rendering issues

---

src/components/form.tsx
src/enums/font-weight.ts
src/styles/main.css
src/types/furniture.d.ts
src/utils/canvas.ts
src/utils/config.ts
src/utils/furniture-helpers.ts
src/utils/text-renderer.ts

This PR adds the ability to set the font weight of the standfirst text. A [requirement for Australia editions](https://trello.com/c/y6yxpZzJ/340-ability-to-select-the-font-weight-of-the-standfirst).
Select an image, enter some text into the various sections. Experiment with changing the standfirst font weight. 
Users are able to set the standfirst font weight appropriately.

Adds the ability to select the standfirst weight

---

src/utils/config.ts

This modifies the height of mobile cards, increasing it to 945px. This is because on phones like the iPhone 5s, due to the narrow screen size cards are much more 'rectangular' than other phone types -so we need a cover card that is almost twice as long as it is high. My calculation for this new height is 1.8x the width, which I got from looking at the iPhone 5s card width/height ratio. 
A second piece of work would be great to do, which is to show a 'safe area' line indicating which parts of an image might be cropped. This should be at 1.3x the width (based off the iphone 11 pro max - a rather wide phone...).
The issue this solves is illustrated below. Lots of background design work can be seen in [figma](https://www.figma.com/file/AgfOrrLI78asahmA3Z9Env/AUS%2FUS-xtra-designs?node-id=1326% …

Increase height of mobile cards to 1.8x width

---

src/utils/config.ts

Reverts guardian/editions-card-builder#77 as it created problems for the production team

Revert "Increase height of mobile cards to 1.8x width"

---

src/components/header.tsx

This PR attempts to reduce the wait times for uploads by reducing the upload image file size. 
This was originally reported by users experiencing long wait times on uploads, especially when they have poorer connections. 
In my testing I have found uploaded images sizes of previously 35mb can be reduced to 6mb. [Before](https://media.test.dev-gutools.co.uk/images/f8d750990175623367a42386ceff5302d94f2c7c) and [after](https://media.test.dev-gutools.co.uk/images/9a8463008046d293ebe80f359e86e090d437af89).
More details can be found on the [trello card](https://trello.com/c/PwXHe1Z9/361-reduce-upload-image-file-size).
**NB** The upload button was being enabled after the blob conversion, which can take some time. Moving this to before the conversion should improve the UX for the upload button. …

Switches the blob mime type to be JPEG instead of PNG

---

src/utils/config.ts

Changes the collection this tool tags generated images with from `iPad Daily Edition` to `UK Daily Edition`, as requested by Edition staff.
Does the tool add generated images to the correct collection?
Tested locally with CODE Grid.
As above.

Change collection target to UK Daily Edition

---

src/utils/config.ts

Sorry for the repeated PRs on this! Reverts guardian/editions-card-builder#81 as it's too severe a crop unfortunately - it results in too great a diff between the images in the grid. Some changes in the grid will be required first

Revert "Increase mobile ratio to 1.7 "

---

package-lock.json
package.json
src/components/image-select.tsx

https://github.com/guardian/editions-card-builder/pull/58 take 2 but a smaller surface area as it doesn't change all the types.
Introduces [grid-client](https://github.com/guardian/grid-client) to this project (the first project to use this library 🎉 ).
The grid-client library provides some abstractions around handling a post message response from Grid, most notably it will validate the message and provides a [function to get the highest quality asset](https://github.com/guardian/grid-client/blob/241f9464ac81684c2e7fd642a9d4270feca44a2c/src/services/crop.ts#L31) in a crop. This function is safer than the current implementation; currently, we're assuming a `master` crop exists, which Grid does not guarantee as the field is [optional](https://github.com/guardian/grid/blob/86731ccab339bd2a275 …

use grid-client for Grid crop validation

---

src/components/form.tsx
src/components/image-select.tsx
src/utils/canvas.ts
src/utils/config.ts

This PR adds a query string to the grid iframe url which makes use of the [custom crop functionality now available in the grid](https://github.com/guardian/grid/pull/3017). This will allow the production team to see exactly what crop they're going to get when selecting images.
The longer term motivation for this work is that we might start needing much taller crops for mobile cover cards, so we want to make users aware of the awkward aspect ratio these might have. This PR does not introduce any aspect ratio changes.
The ratios are a bit crazy right now - e.g. 525:810 - due to the way that the cover card tool currently works out dimensions. I think this could be simplified but wanted to keep as few moving parts as possible for this PR.
I've had a struggle with prettier on this PR, if …

Use grid customcrop query parameter when loading grid iframe

---

src/components/image-select.tsx

This reverts the change in https://github.com/guardian/editions-card-builder/pull/86 with as few code changes as possible...I thought this would be nicer to review on a friday afternoon than a full PR revert. 
I'm not sure what's going on here as https://github.com/guardian/editions-card-builder/pull/86 was rolled out a while ago and the cover card builder's been in regular use since then but all of a sudden people are seeing their crops disappear. I'm hoping this change will resolve that problem.
Steps to reproduce:
- select image - grid opens in iframe
- perform a crop
- at this point you should be taken back to the cover card builder and the crop should be imported. instead you are taken back to the grid

Remove Grid query string

---

package-lock.json
package.json
src/components/image-select.tsx

It appears the grid-client library doesn't work for every possible shape of data Grid responds with. Removing it for the time being.
Related to https://github.com/guardian/editions-card-builder/pull/85.

remove @guadian/grid-client

---

src/components/image-select.tsx

Reverts guardian/editions-card-builder#87 as it looks like the error discussed there was actually caused by https://github.com/guardian/editions-card-builder/pull/85

Revert "Remove Grid query string"

---

package-lock.json
package.json
src/components/image-select.tsx

Reverts guardian/editions-card-builder#88.
Re-introducing `grid-client`. We experienced an issue where this tool could not parse and validate the payload coming from Grid. This was related to Grid sending erroneous data; this is fixed in https://github.com/guardian/grid/pull/3033.
This also re-introduces the [reporter](https://github.com/guardian/grid-client/blob/41b82ab1e0dd9d6836e0812502878b40ffa83ecc/src/utils/reporter.ts) (a wrapper around [`PathReporter`](https://github.com/gcanti/io-ts/blob/46999babe78b08765a573a1a56d5c16233d99f0b/index.md#error-reporters)), which will console [log a detailed message](https://github.com/guardian/grid-client/blob/41b82ab1e0dd9d6836e0812502878b40ffa83ecc/src/services/iframe-post-message.ts#L23) should the Grid payload fail to validate again in the …

Revert "remove @guadian/grid-client"

---

src/components/image-select.tsx
src/utils/canvas.ts
src/utils/config.ts

This PR introduces 2 new config properties - 'cropRatio' and 'safeRatio'. `cropRatio` is what you have to multiply the width by to get the height of the card. `safeRatio` is the area of the image that is 'guaranteed' to appear on the majority of devices - it's currently based off one of the monster wide iphones. 
Using these properties, an  extra transparent rectange is drawn on the canvas showing the area of the image that might be cropped off on certain devices. It's a white 50% opacity box at the moment but I'm open to suggestions for improvements...
As part of this I've removed `cropHeight` as this can be calculated from the ratio. This is a further step towards not having absolute width/height in the cover card tool (they're irrelevant - we only care about aspect ratios).
NOTE: To …

Add safe area overlay on image. 

---

src/utils/canvas.ts

I tested the safe area feature with Katy V this morning and she suggested rolling the safe area feature added in https://github.com/guardian/editions-card-builder/pull/93 back until it can be made more accessible - mainly so that it works on images that are red! It's going to take me a while to get my head round how to do that and she'd rather not have to update the style guide twice with an in flux feature so I said I'd remove this for now so as not to confuse people. I'd prefer not to revert the whole feature as that's already been through code review here https://github.com/guardian/editions-card-builder/pull/93 - there should be a fix for it wiithiin the next couple of days... 
I think this back and forth is another case for allowing testing of dev branches on master as discussed here …

Disable safe area feature pending accessibility improvements.

---

.github/workflows/cd.yml

Replaces reference to 'master' in CD config file. Once this is merged, it will test whether the master-to-main replacement was successful.

Replace reference to master with main in config

---

src/components/form.tsx
src/utils/canvas.ts

This is another (hopefully final stab) at the work discussed in https://github.com/guardian/editions-card-builder/pull/91- which aims to make it clearer to users which bit of the image could get cropped off on wider screen devices.
The changes introduced here change the 'unsafe area' pattern so that it is striped in red and white, which should mean it is visible over all images (even red ones). I wasn't smart enough to red/white diagonal stripes so they're also now horizontal!
As part of this change I've also added some instructions explaining what the safe area is on the left sidebar - Katy thought it might be useful to have something so it's not a suprise.
It looks like this:
The instructions look like this:
Add an image to the card builder in mobile mode - you should see the stripes.

Re-Enable unsafe area with different coloured stripes

---

src/utils/config.ts

The production team have been asking for a while for it to be possible for cover card text to use the full width. In the app we only crop from the bottom upwards, so this seems a sensible change to make.
Before:
After:
Run cover card tool, check that text can span the full width but doesn't run off the edge
Happy production team, no text cropped!
The main risk would be if the app decides to start cropping from the sides, but that would affect a lot of other stuff too so I think we're safe.

Allow full width text on cover cards.

---

.github/workflows/cd.yml
.github/workflows/ci.yml

Adds the [workflow_dispatch](https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/) trigger to make it possible to manually run CI/CD
Go into the [github actions console](https://github.com/guardian/editions-card-builder/actions) then select a branch and run the action on that branch.
Being able to deploy arbitrary branches to PROD, re run CI/CD without having to push code changes. 
It makes it easier to put a development branch on PROD, so should be used with caution. However, this behaviour is already possible via the github api so let's put it in a nice UI!

Add workflow_dispatch github actions trigger.

---

src/utils/config.ts

This changes the aspect ratio of mobile cover cards, making them taller so that they don't have such a large border on iPhone SE.
This has been attempted before, but the hope is that following from the safe area introduced in https://github.com/guardian/editions-card-builder/pull/77 and the grid crop guide introduced here https://github.com/guardian/editions-card-builder/pull/86 this is now a viable ratio for the production team to use. 
Developers: run the tool, observe the 'taller' crop ratio
This feature is likely to need rolling back - the plan is:
- Arrange a time for Katy to test this
- Merge to PROD
- Ask Katy and her team to test
- no good - revert, merge revert
Less whitespace in the editions app
See above - this ratio might be unworkable.

Bump mobile crop ratio to 1.7

---

src/utils/config.ts

Introduces a 'safe area' for tablets. I worked this out by taking a screenshot of a cover card on an ipad pro 12.9 inch, which I think is the biggest. I then worked out what percentage of the image got cropped and applied the same thing in reverse to another cover card to check that it correctly calculated the safe area.
For full details of the safe area feature see https://github.com/guardian/editions-card-builder/pull/91
Deploy, check that a safe area appears on tablet images. 
Happy production team able to relax about tablet images
The safe area could be wrong, in which case cover cards could end up with an unexpected crop off the bottom which could cut through essential bits of the image. I'd argue this would still be an improvement though.
Original cover card:
What users see on an …

Add safe area to tablet cards

---

.github/workflows/cd.yml

Paired on with @rhystmills.
Currently our deploys are [failing](https://github.com/guardian/editions-card-builder/actions/runs/9349575546/job/25731191433) due to an auth error:
```
> gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"
remote: Permission to guardian/editions-card-builder.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/guardian/editions-card-builder.git/': The requested URL returned error: 403
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! editions-card-builder@1.0.0 deploy: `gh-pages -d dist -u "github-actions-bot <support+actions@github.com>"`
npm ERR! Exit status 1
```
Following the pattern outlined in https://github.com/tschaub/gh-pages/issues/429#issuecomment-1126987413, we are adding permissions to the workflow to …

Add permission to workflow
