guardian/editions-card-builder

- .gitignore
- .htmlnanorc
- package-lock.json
- package.json
Use [ParcelJS](https://parceljs.org/) for bundling.
> Add ParcelJS

- src/grid/modal.js
So that if/when you open the Grid modal again, you're shown the same image.
> remember image id

- src/canvas.js
Each time we update the canvas, we get the image and then write to canvas. This results in lots of network calls! Using dataURL means we can use sessionStorage as a cache, meaning we have free performance gains!
> convert image to dataURL before writing to canvas

- src/canvas.js
- src/config.js
- src/main.css
So, the output for this tool was quite lo-res, so what I've done is:
- removed the scale parameter and multiplied it into the constants it was used in 
- calculated an output size and scale factor from the image and used these everywhere
- added a css scale transform to the canvas to restore its size
- bonus: changed the port to not conflict with metro bundler
> use highest res possible output

- package-lock.json
- src/canvas.js
- src/config.js
Supersedes #15 
@blongden73 I've merged my changes into this and also changed standfirstHeight and headlineHeight to use lineheight instead of font size
Making a new PR because I forgot to finish rebasing before I did this,
> Line Height 2

- package-lock.json
- package.json
- src/canvas.js
- src/main.css
- src/main.js
Adds a debounce on the draw 
This also stops magically scaling the canvas and just uses css to give it a height which seems to do much the same thing behind the scenes without changing the styles.
> Perf tweaks

- README.md
- script/format
Add some nice things to readme
> Prettier instructions

- src/canvas.js
This fixes the split at random location issue that was making production :(
> Split strings at spaces and linebreaks

- src/canvas.js
Add scale to remaining places (bugfix from full sized image pr)
> Add scale to remaining places

- package-lock.json
- package.json
- src/index.html
- src/main.js
Calling toDataURL was eating performance with big images.
> Remove download from loop

- src/canvas.js
I added some extra needless whitespace.
> Don't add newline to beginning of new line

- package.json
- src/grid/upload.js
- src/index.html
- src/main.js
I had intended to track progress, but that didn't work.
This re-enables the button on catch from the upload and logs the error message.
> fail slightly better

- src/main.css
This fixes the shrinking sidebard.
> Add min width to left bar

- src/index.html
Correct spelling.
Fewer eye twitches.
> correct spelling

- src/config.js
- src/index.html
- src/main.css
- src/main.js
Custom position becomes nicer to use.
Already demoed to KV
> Tidy up custom position by converting to slider.

- src/main.js
Adds a useful comment.
Useful comment is useful
> Add useful comment

- package-lock.json
- package.json
- src/index.html
Produces semantic HTML. A select requires a label rather than a fieldset.
Related to https://github.com/guardian/editions-card-builder/pull/33.
More correct DOM structure. No-op for the user.
n//a
> produce semantic HTML

- .github/workflows/ci.yml
- script/ci
Uses GitHub Actions for CI.
The project has an automated CI step.
n/a
> use github actions for ci

- .github/workflows/cd.yml
- README.md
- script/cd
Deploy to GitHub Pages when the master branch changes.
This project has automated CD.
n/a
> use github actions for cd

- src/components/canvas.tsx
- src/components/image-select.tsx
- src/styles/main.css
This PR fixes various issues which users were experiencing on the release of the [convert to react PR](https://github.com/guardian/editions-card-builder/pull/44).
The various issues should be fixed. These are:
1. Crops not being propagated into the editor.
2. The canvas rendering on the left and not in the centre.
3. A significant delay between inputs and updates to the canvas.
**NB** The way I have created this PR will require us to revert the revert in order to be able to merge successfully.
> React fixes

- src/components/form.tsx
- src/components/size-picker.tsx
- src/enums/size.ts
- src/styles/main.css
- src/utils/canvas.ts
- src/utils/config.ts
* Headline now has an 'extra large' option
* Font sizing functionality has been pulled out into a new component for flexibility
* Font sizes have been adjusted to meet provided figures.
On local: 
1. Select an image
2. Add some headline text
3. You should now be able to select an 'extra large' font size
> Add extra large font size for headline

- src/components/header.tsx
This PR prevents users from accidentally pressing the download button multiple times, triggering separate download events.
Create an image, press the download button repeatedly, observe the result.
The download dialogue only appears once for users who wish to download an image.
> prevents a user from accidentally downloading an image multiple times

- src/components/form.tsx
- src/components/size-picker.tsx
- src/enums/location.ts
- src/enums/size.ts
- src/styles/main.css
- src/types/furniture.d.ts
- src/utils/canvas.ts
- src/utils/config.ts
- src/utils/furniture-helpers.ts
This PR restores the font size work that was done but rolled-back pending final approval. The previous PR can be found [here](https://github.com/guardian/editions-card-builder/pull/68).
> Restore font size changes

- src/components/image-select.tsx
- src/utils/canvas.ts
- src/utils/config.ts
Reverts guardian/editions-card-builder#91 as it causes the red lines to show on the output image!
> Revert "Add safe area overlay on image. "

- src/components/canvas.tsx
- src/components/image-select.tsx
- src/styles/main.css
- src/utils/canvas.ts
- src/utils/config.ts
This is the same work as in https://github.com/guardian/editions-card-builder/pull/91 but with the  'unsafe area' pattern drawn on a new canvas it doesn't get uploaded to the grid!
> Show safe area attempt 2

- src/utils/canvas.ts
Changes the location of 'bottom' text so that it's no longer outside the 'safe area' of the image. At the moment the production team can't use 'bottom' as it will get cropped off on some devices. Following suggestion from @SHession on the initial safe area PR (https://github.com/guardian/editions-card-builder/pull/91)
When selecting the 'bottom' location for text it should appear just above the safe area:
bottom is useful again
If the safe area isn't corret, bottom will still cause problems - e.g. if there is a super widescreen phone device we haven't thought about. So far we haven't come across a larger device though, so this feels like a good improvement as it moves bottom from being 'definitely dangerous' to 'probably safe'.
> Set text bottom position to just above safe area.

- src/components/header.tsx
- src/grid/upload.ts
- src/types/grid-response.d.ts
This PR adapts the upload process to the new api response introduced in a recent [Grid PR](https://github.com/guardian/grid/pull/3172).
It also attempts to improve the upload process by account for the statuses returned by the new status upload uri.
Setup the project locally, test the upload process works as expecting. Ensuring the uploaded version of the file retains all the appropriate meta data.
> Adapts the upload process to the new grid api response

- README.md
> Whitespace PR to trigger deploy
